export const LANG = {
    en:{
        title: "Introduction",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationem laborum dolor nobis perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationemlaborum dolor nobis perspiciatis!",
        title2: "Discription",
        desc2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationem laborum dolor nobis perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationemlaborum dolor nobis perspiciatis!",
        title3: "Content",
        desc3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationem laborum dolor nobis perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationemlaborum dolor nobis perspiciatis!",
        title4: "Brief",
        desc4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationem laborum dolor nobis perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio maxime quod vero labore sunt saepe placeat officiis dolor. Provident consequatur a, quas ad reprehenderit sapiente exercitationemlaborum dolor nobis perspiciatis!",
    },
    hi:{
        title: "परिचय",
        desc: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
        title2: "विवरण",
        desc2: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
        title3: "सामग्री",
        desc3: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
        title4: "संक्षिप्त",
        desc4: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
    },
    sp:{
        title: "Introducción",
        desc: "La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Ellos nos proporcionarán los resultados a partir de los cuales se verá en nosotros el sabio ejercicio de los dolores de parto! La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Proporcionarán los resultados a partir de los cuales los sabios verán el dolor de los ejercicios de entrenamiento!",
        title2: "Descripción",
        desc2: "La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Ellos nos proporcionarán los resultados a partir de los cuales se verá en nosotros el sabio ejercicio de los dolores de parto! La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Proporcionarán los resultados a partir de los cuales los sabios verán el dolor de los ejercicios de entrenamiento!",
        title3: "Contenido",
        desc3: "La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Ellos nos proporcionarán los resultados a partir de los cuales se verá en nosotros el sabio ejercicio de los dolores de parto! La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Proporcionarán los resultados a partir de los cuales los sabios verán el dolor de los ejercicios de entrenamiento!",
        title4: "Breve",
        desc4: "La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Ellos nos proporcionarán los resultados a partir de los cuales se verá en nosotros el sabio ejercicio de los dolores de parto! La empresa en sí es una empresa muy exitosa. La mejor opción es que trabajan muy duro y, a menudo, les gustan los servicios del cliente. ¡Proporcionarán los resultados a partir de los cuales los sabios verán el dolor de los ejercicios de entrenamiento!",
    },
    ru:{
        title: "Введение",
        desc: "Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мы увидим мудрое осуществление родовых схваток! Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мудрецы увидят боль от тренировок!",
        title2: "Описание",
        desc2: "Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мы увидим мудрое осуществление родовых схваток! Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мудрецы увидят боль от тренировок!",
        title3: "Содержание",
        desc3: "Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мы увидим мудрое осуществление родовых схваток! Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мудрецы увидят боль от тренировок!",
        title4: "Краткий",
        desc4: "Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мы увидим мудрое осуществление родовых схваток! Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мудрецы увидят боль от тренировок!",
    },
    fe:{
        title: "परिचय",
        desc: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
        title2: "विवरण",
        desc2: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
        title3: "सामग्री",
        desc3: "कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे हमें प्रसव पीड़ा का बुद्धिमानीपूर्ण अभ्यास दिखाई देगा! कंपनी अपने आप में एक बेहद सफल कंपनी है. सबसे अच्छा विकल्प यह है कि वे वास्तव में कड़ी मेहनत करते हैं और अक्सर ग्राहक की सेवाओं को पसंद करते हैं। वे परिणाम प्रदान करेंगे जिससे प्रशिक्षण अभ्यास का दर्द बुद्धिमानों को दिखाई देगा!",
        title4: "संक्षिप्त",
        desc4: "Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мы увидим мудрое осуществление родовых схваток! Сама компания очень успешная. Лучший вариант, чтобы они действительно трудолюбивы и им часто нравились услуги заказчика. Они дадут результаты, из которых мудрецы увидят боль от тренировок!"
    },

}